### ISSUE TITLE
Rendering errors with emojis

### ISSUE THREAD

**Issue by heyarne** [rafaelrinaldi/pure#57] opened 2017-11-30 14:03 UTC
I'm not quite sure whether the source of this bug lies in this theme, but when I use emojis there is double rendering of text sometimes. A screenshot might clarify what I mean:

<img width="892" alt="screen shot 2017-11-30 at 14 59 56" src="https://user-images.githubusercontent.com/525780/33434330-4dd8e85c-d5df-11e7-9bfc-7eb079f56f89.png">

The same does not happen with regular characters. The screenshot is of me typing `gc -am 'Make` with the autosuggestion being from an earliert commit message. I'm on macOS 10.13, Terminal.app Version 2.8 (400), Fira Mono 12pt, fish version 2.6.0.

**Comment by edouard-lopez** [comment] 2017-12-21 15:42
@heyarne
Could you paste the content of the line seen above so we can try to reproduce?

**Comment by heyarne** [comment] 2017-12-21 15:44
I'm not quite sure I get the request. The output is:
```
gc -am 'Make naammes of all communities unique (😐) and re-run the notebook'
```

The original commit (gc is aliased to `git commit`) was:
```
gc -am 'Make names of all communities unique (😐) and re-run the notebook'
```

**Comment by edouard-lopez** [comment] 2018-01-02 10:56
I can't reproduce on either Terminus nor Yakuake terminal. Could you try:

1. to simplify your config to narrow down the issue.
1. use `git commit` instead of the alias
1. look for conflicting auto-completiong methods.

**Comment by rafaelrinaldi** [comment] 2018-01-03 16:25
@heyarne This looks like a GUI/Font issue. What terminal application are you using? Is your Fira Mono patched for Powerline?

**Comment by heyarne** [comment] 2018-01-03 16:59
I'm using Terminal.app 2.8 (400), the one shipping with macOS 10.13. A more minimal example:

```
# In any directory
git commit -m '🍾'
```

As soon as I type the closing `'` it looks like this:

<img width="892" alt="screen shot 2018-01-03 at 17 54 37" src="https://user-images.githubusercontent.com/525780/34530352-33e7540c-f0af-11e7-81b8-f6ad8ab2ff0f.png">

When I delete the last backspace this is the result:

<img width="892" alt="screen shot 2018-01-03 at 17 56 05" src="https://user-images.githubusercontent.com/525780/34530418-6551b7d0-f0af-11e7-9030-d0c991a453c6.png">

This happens with different fonts, powerline-patched or not (I tried Menlo, Fira Mono, Fira Code, Monaco, Droid Sans Mono...). iTerm2 3.1.5 does not have the same problem (tested with Monaco / Fira Mono).

I'm pretty sure this is some off-by-one-error caused by the fact that emojis are rendered two characters wide. This is iTerm2 after the closing single quote:

<img width="850" alt="screen shot 2018-01-03 at 17 56 52" src="https://user-images.githubusercontent.com/525780/34530482-93c8c478-f0af-11e7-93cf-7efbca7e719c.png">

See how the quote is behind the champagne bottle? Funny enough, when I first tried making the screenshot my terminal window was in a tabset. I pulled the tab to place it on its own window, getting the following result:

<img width="892" alt="screen shot 2018-01-03 at 17 54 09" src="https://user-images.githubusercontent.com/525780/34530533-bb7f35ec-f0af-11e7-860b-a18f3d6a1bc2.png">

Well.. yea. So pretty sure it's related to Terminal.app. Can anybody else reproduce this?

**Comment by rafaelrinaldi** [comment] 2018-01-03 17:07
This is a fish issue. See: https://github.com/fish-shell/fish-shell/issues/2652

Closing this issue for now. Feel free to open a new one if I missed something or submit a PR with a fix.

**Closed by rafaelrinaldi** 2018-01-03 17:07 UTC
