### ISSUE TITLE
Terminal output newline when pasting or resizing terminal

### ISSUE THREAD

**Issue by pcr910303** [rafaelrinaldi/pure#151] opened 2019-03-18 15:55 UTC
When I open a terminal emulator window and paste anything in it (agnostic to the terminal emulator, e.g. Terminal.app, iTerm2, Alacritty) or resize it, the path indicator is redrawn in the second line(not on the first), and the prompt is redrawn in the third line(not on the second).

[Here's a gif(23MB)](
https://bashupload.com/ZiONY/out.gif) -> It gets expired after 7 days, so please ping me if it's expired :-)

**Comment by edouard-lopez** [comment] 2019-03-18 22:25
Hi @pcr910303,

Could you give us the value for:

    echo $pure_version
    fish --version

Also could you try with [`hyper` terminal](https://github.com/zeit/hyper)?

Ping That's might be a Mac-related issue @rafaelrinaldi @schrodincat

**Comment by pcr910303** [comment] 2019-03-18 23:02
```shell
Last login: Tue Mar 19 07:57:58 on ttys001
~
❯ echo $pure_version 
2.1.1

~
❯ fish --version
fish, version 3.0.2-608-g05b9c078

```

This problem persisted from at least fish 2.7. (I'm currently using a HEAD version for CJK language issues.)

**Comment by pcr910303** [comment] 2019-03-18 23:03
The problem persists with the Hyper terminal. :-(
<img width="328" alt="무제" src="https://user-images.githubusercontent.com/37990858/54569256-80632900-4a1d-11e9-88ad-e89d425717a1.png">

**Comment by schrodincat** [comment] 2019-03-18 23:23
@edouard-lopez it's definitely happening for me too, but I'm not sure this is Mac-related issue

**Comment by edouard-lopez** [comment] 2019-03-19 10:51
It's cross-platform `tmux` was interfering in my test. 

I reproduce the issue for copy/paste and resize only for the first prompt.

Here is some debug information that might help.

<details>
    <summary>fish -d 3</summary>
<pre>
~ master*
❯ <3> fish: Created job 2 from command 'set -g __fish_last_bind_mode $fish_bind_mode' with pgrp -2
<3> fish: Created job 2 from command 'source /usr/share/fish/functions/__fish_commandline_is_singlequoted.fish' with pgrp -2
<3> fish: Created job 2 from command 'set -l state normal' with pgrp -2
<3> fish: Created job 4 from command 'commandline -ct | string split ""' with pgrp 5414
<3> fish: Created job 4 from command 'contains -- $state single single-escaped' with pgrp -2
<3> fish: Created job 2 from command 'return 1' with pgrp -2
<3> fish: Created job 3 from command '__fish_commandline_is_singlequoted' with pgrp -2
<3> fish: Created job 1 from command '__fish_start_bracketed_paste' with pgrp -2
echo $pure_version <3> fish: Created job 2 from command 'set fish_bind_mode $__fish_last_bind_mode' with pgrp -2
<3> fish: Created job 3 from command 'set -e __fish_paste_quoted' with pgrp -2
<3> fish: Created job 2 from command 'commandline -f force-repaint' with pgrp -2
<3> fish: Created job 1 from command '__fish_stop_bracketed_paste' with pgrp -2
<3> fish: Created job 2 from command 'set --local exit_code $status' with pgrp -2
<3> fish: Created job 4 from command 'set --local new_line' with pgrp -2
<3> fish: Created job 5 from command 'test $_pure_fresh_session = false' with pgrp -2
<3> fish: Created job 4 from command 'set new_line "\n"' with pgrp -2
<3> fish: Created job 4 from command 'set --local new_line "$new_line\r\033[K"' with pgrp -2
<3> fish: Created job 5 from command 'echo $new_line' with pgrp -2
<3> fish: Created job 2 from command '_pure_prompt_beginning' with pgrp -2
<3> fish: Created job 3 from command 'echo -e -n (_pure_prompt_beginning)' with pgrp -2
<3> fish: Created job 5 from command 'set -q argv[1]' with pgrp -2
<3> fish: Created job 6 from command 'set -l options 'h/help' 'a/all' 'f/no-functions' 't/type' 'p/path' 'P/force-path' 'q/quiet'' with pgrp -2
<3> fish: Created job 5 from command 'argparse -n type -x t,p,P $options -- $argv' with pgrp -2
<3> fish: Created job 6 from command 'set -q _flag_help' with pgrp -2
<3> fish: Created job 5 from command 'set -l res 1' with pgrp -2
<3> fish: Created job 6 from command 'set -l mode normal' with pgrp -2
<3> fish: Created job 5 from command 'set -l multi no' with pgrp -2
<3> fish: Created job 6 from command 'set -l selection all' with pgrp -2
<3> fish: Created job 5 from command 'set -q _flag_quiet' with pgrp -2
<3> fish: Created job 6 from command 'set mode quiet' with pgrp -2
<3> fish: Created job 6 from command 'set -q _flag_all' with pgrp -2
<3> fish: Created job 5 from command 'set -q _flag_no_functions' with pgrp -2
<3> fish: Created job 6 from command 'set selection files' with pgrp -2
<3> fish: Created job 5 from command 'set -l found 0' with pgrp -2
<3> fish: Created job 7 from command 'test $selection != files' with pgrp -2
<3> fish: Created job 5 from command 'set -l paths' with pgrp -2
<3> fish: Created job 7 from command 'test $multi != yes' with pgrp -2
<3> fish: Created job 8 from command 'command -s -- $i' with pgrp -2
<3> fish: Created job 5 from command 'set paths (command -s -- $i)' with pgrp -2
<3> fish: Created job 5 from command 'set res 0' with pgrp -2
<3> fish: Created job 8 from command 'set found 1' with pgrp -2
<3> fish: Created job 5 from command 'test $multi != yes' with pgrp -2
<3> fish: Created job 8 from command 'continue' with pgrp -2
<3> fish: Created job 5 from command 'test $found = 0' with pgrp -2
<3> fish: Created job 5 from command 'return $res' with pgrp -2
<3> fish: Created job 4 from command 'not type -fq git' with pgrp -2
<3> fish: Created job 7 from command 'test "$SSH_CONNECTION" != ""' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_ssh' with pgrp -2
<3> fish: Created job 8 from command 'command git rev-parse --is-inside-work-tree 2>/dev/null' with pgrp 5136
<3> fish: Created job 7 from command 'set --local is_git_repository (command git rev-parse --is-inside-work-tree 2>/dev/null)' with pgrp -2
<3> fish: Created job 8 from command 'test -n "$is_git_repository"' with pgrp -2
<3> fish: Created job 12 from command 'command git symbolic-ref --short HEAD 2>/dev/null' with pgrp 5136
<3> fish: Created job 11 from command '_pure_parse_git_branch' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_branch (_pure_parse_git_branch)' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_branch_color "$pure_color_git_branch"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_branch_color$git_branch"' with pgrp -2
<3> fish: Created job 9 from command '_pure_prompt_git_branch' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_dirty_symbol' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_dirty_color' with pgrp -2
<3> fish: Created job 11 from command 'command git status --porcelain --ignore-submodules 2>/dev/null' with pgrp 5136
<3> fish: Created job 10 from command 'set --local is_git_dirty (command git status --porcelain --ignore-submodules 2>/dev/null)' with pgrp -2
<3> fish: Created job 11 from command 'test -n "$is_git_dirty"' with pgrp -2
<3> fish: Created job 10 from command 'set git_dirty_symbol "$pure_symbol_git_dirty"' with pgrp -2
<3> fish: Created job 12 from command 'set git_dirty_color "$pure_color_git_dirty"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_dirty_color$git_dirty_symbol"' with pgrp -2
<3> fish: Created job 9 from command '_pure_prompt_git_dirty' with pgrp -2
<3> fish: Created job 7 from command 'set --local git_prompt (_pure_prompt_git_branch)(_pure_prompt_git_dirty)' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_unpushed_commits' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_unpulled_commits' with pgrp -2
<3> fish: Created job 11 from command 'command git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null' with pgrp 5136
<3> fish: Created job 10 from command 'set --local has_upstream (command git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null)' with pgrp -2
<3> fish: Created job 11 from command 'test -n "$has_upstream"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_unpushed_commits$git_unpulled_commits"' with pgrp -2
<3> fish: Created job 7 from command '_pure_prompt_git_pending_commits' with pgrp -2
<3> fish: Created job 9 from command 'set --local git_pending_commits (_pure_prompt_git_pending_commits)' with pgrp -2
<3> fish: Created job 10 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 10 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 11 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 10 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 9 from command '_pure_string_width $git_pending_commits' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $git_pending_commits) -ne 0' with pgrp -2
<3> fish: Created job 9 from command 'echo $git_prompt' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_git' with pgrp -2
<3> fish: Created job 7 from command 'set --local command_duration' with pgrp -2
<3> fish: Created job 8 from command 'test -n "$CMD_DURATION"' with pgrp -2
<3> fish: Created job 10 from command 'test $milliseconds -lt 0' with pgrp -2
<3> fish: Created job 10 from command 'math -s0 "$milliseconds / 1000 % 60"' with pgrp -2
<3> fish: Created job 11 from command 'set --local seconds (math -s0 "$milliseconds / 1000 % 60")' with pgrp -2
<3> fish: Created job 11 from command 'math -s0 "$milliseconds / 60000 % 60"' with pgrp -2
<3> fish: Created job 10 from command 'set --local minutes (math -s0 "$milliseconds / 60000 % 60")' with pgrp -2
<3> fish: Created job 10 from command 'math -s0 "$milliseconds / 3600000 % 24"' with pgrp -2
<3> fish: Created job 11 from command 'set --local hours (math -s0 "$milliseconds / 3600000 % 24")' with pgrp -2
<3> fish: Created job 11 from command 'math -s0 "$milliseconds / 86400000"' with pgrp -2
<3> fish: Created job 10 from command 'set --local days (math -s0 "$milliseconds / 86400000")' with pgrp -2
<3> fish: Created job 11 from command 'set --local time' with pgrp -2
<3> fish: Created job 10 from command 'test $days -gt 0' with pgrp -2
<3> fish: Created job 11 from command 'test $hours -gt 0' with pgrp -2
<3> fish: Created job 10 from command 'test $minutes -gt 0' with pgrp -2
<3> fish: Created job 11 from command 'test $seconds -gt $threshold' with pgrp -2
<3> fish: Created job 11 from command 'string join ' ' $time' with pgrp -2
<3> fish: Created job 10 from command 'echo -e (string join ' ' $time)' with pgrp -2
<3> fish: Created job 9 from command '_pure_format_time $CMD_DURATION $pure_threshold_command_duration' with pgrp -2
<3> fish: Created job 7 from command 'set command_duration (_pure_format_time $CMD_DURATION $pure_threshold_command_duration)' with pgrp -2
<3> fish: Created job 7 from command 'set --local command_duration_color "$pure_color_command_duration"' with pgrp -2
<3> fish: Created job 8 from command 'echo "$command_duration_color$command_duration"' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_command_duration' with pgrp -2
<3> fish: Created job 6 from command 'set --local prompt' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 8 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 8 from command 'set prompt "$prompt $prompt_part"' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 7 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 8 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 6 from command 'string trim -l $prompt' with pgrp -2
<3> fish: Created job 7 from command 'echo (string trim -l $prompt)' with pgrp -2
<3> fish: Created job 4 from command '_pure_print_prompt \
                            (_pure_prompt_ssh) \
                            (_pure_prompt_git) \
                            (_pure_prompt_command_duration)' with pgrp -2
<3> fish: Created job 5 from command 'set --local prompt (_pure_print_prompt \
                            (_pure_prompt_ssh) \
                            (_pure_prompt_git) \
                            (_pure_prompt_command_duration)
                        )' with pgrp -2
<3> fish: Created job 6 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 6 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 7 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 6 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 5 from command '_pure_string_width $prompt' with pgrp -2
<3> fish: Created job 4 from command 'set --local prompt_width (_pure_string_width $prompt)' with pgrp -2
<3> fish: Created job 6 from command 'test -z "$current_prompt_width"' with pgrp -2
<3> fish: Created job 8 from command 'math $COLUMNS - $current_prompt_width - 1' with pgrp -2
<3> fish: Created job 9 from command 'string replace $HOME '~' $PWD' with pgrp -2
<3> fish: Created job 8 from command 'set --local folder (string replace $HOME '~' $PWD)' with pgrp -2
<3> fish: Created job 9 from command 'test -n "$max_path_length"' with pgrp -2
<3> fish: Created job 10 from command 'string length $folder' with pgrp -2
<3> fish: Created job 8 from command 'test (string length $folder) -gt $max_path_length' with pgrp -2
<3> fish: Created job 8 from command 'echo $folder' with pgrp -2
<3> fish: Created job 6 from command '_pure_parse_directory (math $COLUMNS - $current_prompt_width - 1)' with pgrp -2
<3> fish: Created job 7 from command 'set --local current_folder (_pure_parse_directory (math $COLUMNS - $current_prompt_width - 1))' with pgrp -2
<3> fish: Created job 6 from command 'set --local current_folder_color "$pure_color_current_directory"' with pgrp -2
<3> fish: Created job 7 from command 'echo "$current_folder_color$current_folder"' with pgrp -2
<3> fish: Created job 4 from command '_pure_prompt_current_folder $prompt_width' with pgrp -2
<3> fish: Created job 5 from command 'set --local current_folder (_pure_prompt_current_folder $prompt_width)' with pgrp -2
<3> fish: Created job 4 from command 'set --local prompt_components' with pgrp -2
<3> fish: Created job 5 from command 'test $pure_begin_prompt_with_current_directory = true' with pgrp -2
<3> fish: Created job 7 from command 'test -z "$current_prompt_width"' with pgrp -2
<3> fish: Created job 9 from command 'math $COLUMNS - $current_prompt_width - 1' with pgrp -2
<3> fish: Created job 10 from command 'string replace $HOME '~' $PWD' with pgrp -2
<3> fish: Created job 9 from command 'set --local folder (string replace $HOME '~' $PWD)' with pgrp -2
<3> fish: Created job 10 from command 'test -n "$max_path_length"' with pgrp -2
<3> fish: Created job 11 from command 'string length $folder' with pgrp -2
<3> fish: Created job 9 from command 'test (string length $folder) -gt $max_path_length' with pgrp -2
<3> fish: Created job 9 from command 'echo $folder' with pgrp -2
<3> fish: Created job 7 from command '_pure_parse_directory (math $COLUMNS - $current_prompt_width - 1)' with pgrp -2
<3> fish: Created job 8 from command 'set --local current_folder (_pure_parse_directory (math $COLUMNS - $current_prompt_width - 1))' with pgrp -2
<3> fish: Created job 7 from command 'set --local current_folder_color "$pure_color_current_directory"' with pgrp -2
<3> fish: Created job 8 from command 'echo "$current_folder_color$current_folder"' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_current_folder $prompt_width' with pgrp -2
<3> fish: Created job 8 from command 'command git rev-parse --is-inside-work-tree 2>/dev/null' with pgrp 5136
<3> fish: Created job 7 from command 'set --local is_git_repository (command git rev-parse --is-inside-work-tree 2>/dev/null)' with pgrp -2
<3> fish: Created job 8 from command 'test -n "$is_git_repository"' with pgrp -2
<3> fish: Created job 12 from command 'command git symbolic-ref --short HEAD 2>/dev/null' with pgrp 5136
<3> fish: Created job 11 from command '_pure_parse_git_branch' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_branch (_pure_parse_git_branch)' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_branch_color "$pure_color_git_branch"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_branch_color$git_branch"' with pgrp -2
<3> fish: Created job 9 from command '_pure_prompt_git_branch' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_dirty_symbol' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_dirty_color' with pgrp -2
<3> fish: Created job 11 from command 'command git status --porcelain --ignore-submodules 2>/dev/null' with pgrp 5136
<3> fish: Created job 10 from command 'set --local is_git_dirty (command git status --porcelain --ignore-submodules 2>/dev/null)' with pgrp -2
<3> fish: Created job 11 from command 'test -n "$is_git_dirty"' with pgrp -2
<3> fish: Created job 10 from command 'set git_dirty_symbol "$pure_symbol_git_dirty"' with pgrp -2
<3> fish: Created job 12 from command 'set git_dirty_color "$pure_color_git_dirty"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_dirty_color$git_dirty_symbol"' with pgrp -2
<3> fish: Created job 9 from command '_pure_prompt_git_dirty' with pgrp -2
<3> fish: Created job 7 from command 'set --local git_prompt (_pure_prompt_git_branch)(_pure_prompt_git_dirty)' with pgrp -2
<3> fish: Created job 10 from command 'set --local git_unpushed_commits' with pgrp -2
<3> fish: Created job 11 from command 'set --local git_unpulled_commits' with pgrp -2
<3> fish: Created job 11 from command 'command git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null' with pgrp 5136
<3> fish: Created job 10 from command 'set --local has_upstream (command git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null)' with pgrp -2
<3> fish: Created job 11 from command 'test -n "$has_upstream"' with pgrp -2
<3> fish: Created job 10 from command 'echo "$git_unpushed_commits$git_unpulled_commits"' with pgrp -2
<3> fish: Created job 7 from command '_pure_prompt_git_pending_commits' with pgrp -2
<3> fish: Created job 9 from command 'set --local git_pending_commits (_pure_prompt_git_pending_commits)' with pgrp -2
<3> fish: Created job 10 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 10 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 11 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 10 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 9 from command '_pure_string_width $git_pending_commits' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $git_pending_commits) -ne 0' with pgrp -2
<3> fish: Created job 9 from command 'echo $git_prompt' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_git' with pgrp -2
<3> fish: Created job 7 from command 'test "$SSH_CONNECTION" != ""' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_ssh' with pgrp -2
<3> fish: Created job 7 from command 'set --local command_duration' with pgrp -2
<3> fish: Created job 8 from command 'test -n "$CMD_DURATION"' with pgrp -2
<3> fish: Created job 10 from command 'test $milliseconds -lt 0' with pgrp -2
<3> fish: Created job 10 from command 'math -s0 "$milliseconds / 1000 % 60"' with pgrp -2
<3> fish: Created job 11 from command 'set --local seconds (math -s0 "$milliseconds / 1000 % 60")' with pgrp -2
<3> fish: Created job 11 from command 'math -s0 "$milliseconds / 60000 % 60"' with pgrp -2
<3> fish: Created job 10 from command 'set --local minutes (math -s0 "$milliseconds / 60000 % 60")' with pgrp -2
<3> fish: Created job 10 from command 'math -s0 "$milliseconds / 3600000 % 24"' with pgrp -2
<3> fish: Created job 11 from command 'set --local hours (math -s0 "$milliseconds / 3600000 % 24")' with pgrp -2
<3> fish: Created job 11 from command 'math -s0 "$milliseconds / 86400000"' with pgrp -2
<3> fish: Created job 10 from command 'set --local days (math -s0 "$milliseconds / 86400000")' with pgrp -2
<3> fish: Created job 11 from command 'set --local time' with pgrp -2
<3> fish: Created job 10 from command 'test $days -gt 0' with pgrp -2
<3> fish: Created job 11 from command 'test $hours -gt 0' with pgrp -2
<3> fish: Created job 10 from command 'test $minutes -gt 0' with pgrp -2
<3> fish: Created job 11 from command 'test $seconds -gt $threshold' with pgrp -2
<3> fish: Created job 11 from command 'string join ' ' $time' with pgrp -2
<3> fish: Created job 10 from command 'echo -e (string join ' ' $time)' with pgrp -2
<3> fish: Created job 9 from command '_pure_format_time $CMD_DURATION $pure_threshold_command_duration' with pgrp -2
<3> fish: Created job 7 from command 'set command_duration (_pure_format_time $CMD_DURATION $pure_threshold_command_duration)' with pgrp -2
<3> fish: Created job 7 from command 'set --local command_duration_color "$pure_color_command_duration"' with pgrp -2
<3> fish: Created job 8 from command 'echo "$command_duration_color$command_duration"' with pgrp -2
<3> fish: Created job 6 from command '_pure_prompt_command_duration' with pgrp -2
<3> fish: Created job 4 from command 'set prompt_components \
                (_pure_prompt_current_folder $prompt_width) \
                (_pure_prompt_git) \
                (_pure_prompt_ssh) \
                (_pure_prompt_command_duration)' with pgrp -2
<3> fish: Created job 6 from command 'set --local prompt' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 8 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 8 from command 'set prompt "$prompt $prompt_part"' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 7 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 8 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 7 from command 'set prompt "$prompt $prompt_part"' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 8 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 6 from command 'string trim -l $prompt' with pgrp -2
<3> fish: Created job 7 from command 'echo (string trim -l $prompt)' with pgrp -2
<3> fish: Created job 5 from command '_pure_print_prompt $prompt_components' with pgrp -2
<3> fish: Created job 4 from command 'echo (_pure_print_prompt $prompt_components)' with pgrp -2
<3> fish: Created job 3 from command '_pure_prompt_first_line' with pgrp -2
<3> fish: Created job 2 from command 'echo -e (_pure_prompt_first_line)' with pgrp -2
<3> fish: Created job 6 from command 'test -n "$VIRTUAL_ENV"' with pgrp -2
<3> fish: Created job 5 from command '_pure_prompt_virtualenv' with pgrp -2
<3> fish: Created job 4 from command 'set --local virtualenv (_pure_prompt_virtualenv)' with pgrp -2
<3> fish: Created job 6 from command 'test ! $pure_reverse_prompt_symbol_in_vimode' with pgrp -2
<3> fish: Created job 4 from command '_pure_prompt_vimode' with pgrp -2
<3> fish: Created job 5 from command 'set --local vimode_indicator (_pure_prompt_vimode)' with pgrp -2
<3> fish: Created job 8 from command 'set --local prompt_symbol $pure_symbol_prompt' with pgrp -2
<3> fish: Created job 8 from command 'string match -r "fish_(vi|hybrid)_key_bindings" $fish_key_bindings' with pgrp -2
<3> fish: Created job 9 from command 'set --local is_vi_mode (string match -r "fish_(vi|hybrid)_key_bindings" $fish_key_bindings)' with pgrp -2
<3> fish: Created job 8 from command 'test -n "$is_vi_mode" \
            -a "$pure_reverse_prompt_symbol_in_vimode" = true \
            -a "$fish_bind_mode" != "insert"' with pgrp -2
<3> fish: Created job 9 from command 'echo "$prompt_symbol"' with pgrp -2
<3> fish: Created job 7 from command '_pure_get_prompt_symbol' with pgrp -2
<3> fish: Created job 6 from command 'set --local prompt_symbol (_pure_get_prompt_symbol)' with pgrp -2
<3> fish: Created job 7 from command 'set --local command_succeed 0' with pgrp -2
<3> fish: Created job 6 from command 'set --local color_symbol $pure_color_prompt_on_success' with pgrp -2
<3> fish: Created job 7 from command 'test $exit_code -ne $command_succeed' with pgrp -2
<3> fish: Created job 6 from command 'echo "$color_symbol$prompt_symbol"' with pgrp -2
<3> fish: Created job 5 from command '_pure_prompt_symbol $exit_code' with pgrp -2
<3> fish: Created job 4 from command 'set --local pure_symbol (_pure_prompt_symbol $exit_code)' with pgrp -2
<3> fish: Created job 6 from command 'set --local prompt' with pgrp -2
<3> fish: Created job 9 from command 'set --local empty ''' with pgrp -2
<3> fish: Created job 9 from command 'string replace --all --regex '\e\[[^m]*m' $empty $prompt' with pgrp -2
<3> fish: Created job 10 from command 'set --local raw_prompt (string replace --all --regex '\e\[[^m]*m' $empty $prompt)' with pgrp -2
<3> fish: Created job 9 from command 'string length $raw_prompt' with pgrp -2
<3> fish: Created job 8 from command '_pure_string_width $prompt_part' with pgrp -2
<3> fish: Created job 7 from command 'test (_pure_string_width $prompt_part) -gt 0' with pgrp -2
<3> fish: Created job 8 from command 'set prompt "$prompt $prompt_part"' with pgrp -2
<3> fish: Created job 6 from command 'string trim -l $prompt' with pgrp -2
<3> fish: Created job 7 from command 'echo (string trim -l $prompt)' with pgrp -2
<3> fish: Created job 4 from command '_pure_print_prompt $virtualenv $vimode_indicator $pure_symbol' with pgrp -2
<3> fish: Created job 5 from command 'echo (_pure_print_prompt $virtualenv $vimode_indicator $pure_symbol)' with pgrp -2
<3> fish: Created job 2 from command '_pure_prompt $exit_code' with pgrp -2
<3> fish: Created job 3 from command 'echo -e -n (_pure_prompt $exit_code)' with pgrp -2
<3> fish: Created job 4 from command 'echo "$pure_color_normal "' with pgrp -2
<3> fish: Created job 3 from command '_pure_prompt_ending' with pgrp -2
<3> fish: Created job 2 from command 'echo -e (_pure_prompt_ending)' with pgrp -2
<3> fish: Created job 3 from command 'set _pure_fresh_session false' with pgrp -2
<3> fish: Created job 1 from command 'fish_prompt' with pgrp -2
<3> fish: Created job 2 from command 'printf "%s%s%s" $pure_color_right_prompt "$pure_right_prompt" $pure_color_normal' with pgrp -2
<3> fish: Created job 1 from command 'fish_right_prompt' with pgrp -2
<3> fish: Created job 3 from command 'string replace -r '^.*/' '' -- $PWD' with pgrp -2
<3> fish: Created job 2 from command 'set --local basename (string replace -r '^.*/' '' -- $PWD)' with pgrp -2
<3> fish: Created job 5 from command 'string replace $HOME '~' $PWD' with pgrp -2
<3> fish: Created job 4 from command 'set --local folder (string replace $HOME '~' $PWD)' with pgrp -2
<3> fish: Created job 5 from command 'test -n "$max_path_length"' with pgrp -2
<3> fish: Created job 4 from command 'echo $folder' with pgrp -2
<3> fish: Created job 2 from command '_pure_parse_directory' with pgrp -2
<3> fish: Created job 3 from command 'set --local current_folder (_pure_parse_directory)' with pgrp -2
<3> fish: Created job 3 from command 'status current-command 2>/dev/null' with pgrp -2
<3> fish: Created job 2 from command 'set --local current_command (status current-command 2>/dev/null; or echo $_)' with pgrp -2
<3> fish: Created job 3 from command 'set --local prompt "$basename: $last_command $pure_symbol_title_bar_separator $current_command"' with pgrp -2
<3> fish: Created job 2 from command 'test -z "$last_command"' with pgrp -2
<3> fish: Created job 3 from command 'set prompt "$current_folder $pure_symbol_title_bar_separator $current_command"' with pgrp -2
<3> fish: Created job 3 from command 'echo $prompt' with pgrp -2
<3> fish: Created job 1 from command 'fish_title' with pgrp -2
~ master*
❯ echo $pure_version <3> fish: Created job 2 from command 'complete -c echo -s n -d "Do not output a newline"' with pgrp -2
<3> fish: Created job 3 from command 'complete -c echo -s s -d "Do not separate arguments with spaces"' with pgrp -2
<3> fish: Created job 2 from command 'complete -c echo -s E -d "Disable backslash escapes"' with pgrp -2
<3> fish: Created job 3 from command 'complete -c echo -s e -d "Enable backslash escapes"' with pgrp -2
<3> fish: Created job 2 from command 'complete -c echo -s h -l help -d "Display help and exit"' with pgrp -2
<3> fish: Created job 1 from command 'source /usr/share/fish/completions/echo.fish' with pgrp -2
</pre>
</details>

**Comment by edouard-lopez** [comment] 2019-03-19 11:00
@faho is this related to binding mode?

**Comment by schrodincat** [comment] 2019-03-19 11:35
What is probably happening is that fish reprints prompt on terminal resize, but we are only erasing current line before printing the prompt. As a result the second line of the prompt gets updated, but the first one is not.

Can we even erase previous line of the terminal?

If so, the first thing on my mind would be to test for previous executed command to determine if it was `pure` invocation and if it was erase two lines instead of one.

**Comment by pcr910303** [comment] 2019-03-19 12:24
@schrodincat Well, if it’s that case on every window resize that should happen, However that only happens on the first prompt: On second or third prompt, everything works as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schrodincat** [comment] 2019-03-19 13:27
Working on it

**Comment by schrodincat** [comment] 2019-03-20 14:06
@pcr910303 the issue is fixed in 2.1.2, please update `pure` with your favourite package manager and thanks for reporting!

**Comment by pcr910303** [comment] 2019-03-20 16:12
@schrodincat Great! Can confirm it is fixed :-) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jgierer12** [comment] 2019-03-21 17:02
Not sure if this is the same issue, but pressing <kbd>Ctrl</kbd> + <kbd>C</kbd> while there is already some text written in the current command line still causes the wrong redraw with `pure v2.1.2`:

![](https://thumbs.gfycat.com/FakeInbornIguanodon-size_restricted.gif)

**Comment by schrodincat** [comment] 2019-03-21 21:04
@jgierer12 it's different issue. Can you elaborate a bit more, what OS, Terminal emulator and `fish` version are you using?

**Comment by jgierer12** [comment] 2019-03-21 21:15
OS: Manjaro Linux x86_64 (Kernel: 5.0.1-1-MANJARO)
Terminal: GNOME Terminal (can also be observed in VSCode integrated terminal)
fish: version 3.0.2

**Comment by johnfraney** [comment] 2019-03-21 21:41
@schrodincat I can confirm this on Arch with Terminix, VS Code's integrated terminal, Gnome Terminal, and Guake running fish 3.0.2. It's happened with this theme as long as I can remember.

**Comment by schrodincat** [comment] 2019-03-22 14:47
@edouard-lopez do you have same issues on your Linux setup? It seems to be Linux specific, as I'm not experiencing this on macOS.

**Comment by edouard-lopez** [comment] 2019-03-28 09:30
Initial issue is solved. However, I can reproduce @jgierer12's one, I'm creating a new issue.

**Closed by edouard-lopez** 2019-03-28 09:30 UTC
Labels: ☹ bug, 🙏 help wanted
